### ISSUE TITLE
Some shapes are not resized on import

### ISSUE THREAD

**Issue by 0x4d** [renew-js/renew-lib#134]
## Describe the bug
The element size is updated and the outline reflects it, however the element graphics do not.

## To Reproduce
1. Draw place in renew
2. Export as PNML
3. Import in renew-js

## Expected behavior
Shapes should have the sizes that is specified in the import file.

**Comment by tim-kilian** [comment]
The initial representation is not updated after the creation on the import. This should be handled on each create process because you can modify the widths and heigths in the factory with your prefered values.
