### ISSUE TITLE
Logo is selectable

### ISSUE THREAD

**Issue by 0x4d** [renew-js/renew-lib#69]
## Describe the bug
The main logo on the top left is selectable.

## To Reproduce
Just selected with your mouse.
Unfortunately, this tends to happen when drawing a connection and moving to the top left out of the canvas.

## Expected behavior
Logo image is not selectable, just clickable.

**Comment by tim-kilian** [comment]
I think thats an issue of the ui. I'll create an issue and reference this one there.

**Comment by 0x4d** [comment]
Thanks! You are absolutely right, didn't think that far when opening this.
