### ISSUE TITLE
Add tests for Viewer, Modeler, Simulator

### ISSUE THREAD

**Issue by 0x4d** [renew-js/renew-lib#74]
## Problem
All tests use a custom Tester instance, which is good, however our three main instance classes should also be tested

**Comment by tim-kilian** [comment]
I understand your need, but I dont know what tests you'd want to put there. Do you just want to ensure, that some modules are loaded or do you want to ensure some functionality? I see some potential tests for the methods in these instances.

**Comment by tim-kilian** [comment]
> I am open to suggestions about the structure of the tests.

As these tests arn't modules there has to be a different structure for it.
