### ISSUE TITLE
Shape under labels are hard reachable

### ISSUE THREAD

**Issue by tim-kilian** [renew-js/renew-lib#94]
## Problem
Currently the whole shape is the hitbox of labels. As labels often overlay other shapes it nessesary for the user expierience to only select the label if the text is hitted.

**Comment by 0x4d** [comment]
BPMN.io also has this issue but it is less severe because they use smaller label box sizes. Maybe we should start with that.

**Comment by tim-kilian** [comment]
We should make the label box smaller too.

**Comment by tim-kilian** [comment]
We could check in the click event listener of the text element, if the text element got hit.
